### ISSUE TITLE
Probably false alarm on "logging.file.X" group of properties

### ISSUE THREAD

**Issue by clayly** [eltonsandre/intellij-spring-boot-helper#1]
Screenshot attached.

![image](https://user-images.githubusercontent.com/31773799/183770200-cc05c4a6-f557-42fd-a0ce-0c770ce6caec.png)

**Comment by eltonsandre** [comment]
Hi @clayly,

Depending on the Spring Boot version, some properties are deprecated, with some warning severity levels and other error severities this might be the case.

Can you give me details of the version of Spring Boot you are using, or even the current dependencies so I can reproduce it here?

**Comment by clayly** [comment]
Hi, thx for quick response.

Latest version for now, Spring Boot 2.7.2.

**Comment by eltonsandre** [comment]
Hi @clayly,

Fixed in plugin version 2022.2.2

**Comment by clayly** [comment]
Yes, looks like it's all good now. Thank you!
