### ISSUE TITLE
Spring Initializr cannot be used in the internal network.

### ISSUE THREAD

**Issue by mabaiqiu** [eltonsandre/intellij-spring-boot-helper#12]
In the internal network, I am unable to use the Spring Initializr plugin. The version I am using is [2022.4.3], and it is showing an error message "error while fetching metadata from server https://start.spring.io". I would like to configure the plugin to use an internal Spring Initializr URL instead.

**Comment by eltonsandre** [comment]
Hi @mabaiqiu 
Please try with the [spring-initializr](https://plugins.jetbrains.com/plugin/23564-spring-initializr) plugin. It was isolated and fixed.
