### ISSUE TITLE
The Spring Boot Helper plugin is not visible in the "New project" list

### ISSUE THREAD

**Issue by benerobert** [eltonsandre/intellij-spring-boot-helper#14]
Hi! 

I'm using IDEA 2024.1 Community Edition and I have the problem that I can't create a new Spring Boot project using the plugin because the plugin is missing from the menu. I use the latest version of the Spring Boot Helper plugin. 

![image](https://github.com/eltonsandre/intellij-spring-boot-helper/assets/128474016/37ea204e-b873-4787-9f4d-c2c36414b647)

The plugin is missing from the list. This is shown instead:

![image](https://github.com/eltonsandre/intellij-spring-boot-helper/assets/128474016/9c3bb529-2a31-444a-905c-1d9b2c127a1c)

**Comment by eltonsandre** [comment]
Hi @benerobert,

from version 2023.1 this module was moved to plugin https://plugins.jetbrains.com/plugin/23564-spring-initializr

**Comment by benerobert** [comment]
Hi! @eltonsandre 
Okay, thank you.
