### ISSUE TITLE
The 2022.2.2 version of the plugin will have a pop-up window after build or maven refresh

### ISSUE THREAD

**Issue by chenmingjun2** [eltonsandre/intellij-spring-boot-helper#4]
I am using IDEA 2022.1.1 community edition, but after installing the 2022.2.2 version of the plugin, every time I build or refresh maven, there will be a Annoying popups. This is affecting my work, can you fix this bug?
this is the pop-up window
**
![image](https://user-images.githubusercontent.com/111257814/184563784-bf50a352-7f27-45f4-a594-0e12ac98c736.png)
**
this is my idea version
![image](https://user-images.githubusercontent.com/111257814/184563806-60adf555-70f5-4e06-a743-49aed7a65c24.png)
this is my system
![image](https://user-images.githubusercontent.com/111257814/184563876-94aee5c1-a265-445e-aace-371df477a8f6.png)

**Comment by chenmingjun2** [comment]
Uploading 录屏_jetbrains-idea-ce_20220815094101.mp4…

**Comment by chenmingjun2** [comment]
https://user-images.githubusercontent.com/111257814/184564132-6d1f8d2e-67d1-471d-bbca-e4a4ff55a922.mp4

**Comment by eltonsandre** [comment]
Hi @chenmingjun2 

The IDE can't verify your license, which is pretty weird. Your case is isolated.
I will investigate the case! And a possible solution.

But until then, make sure you have internet access and try logging out of your JetBrains account and logging in again to reload the license validation.

**Comment by ChingizNamazovSetronica** [comment]
i have the same problem here
lxanl - my jb account
