### ISSUE TITLE
Auto configuration prompt in new window

### ISSUE THREAD

**Issue by xbzhang1994** [eltonsandre/intellij-spring-boot-helper#6]
When I use the idea to open the first project, the plug-in works normally. But when I open the second project (Maven project) and choose to open it in a new window, the spring initializer and assistant (version: 2022.1.2) plug-in cannot automatically configure the prompt.

**Comment by eltonsandre** [comment]
Hi @18856317221 

Could it generate more evidence of what's happening (videos or snapshots) and the stack trace in case it's throwing an exception?

**Comment by xbzhang1994** [comment]
There is no exception. The simple spring boot item in the second window cannot automatically prompt. It is always the first window opened to get the prompt.
